### ISSUE TITLE
We need the home page formatted and prepared for hosting.

### ISSUE THREAD

**Issue by theitsystem** [theitsystem/PiZa#1]

**Comment by flowstyleliving** [comment]
I can do that

**Comment by flowstyleliving** [comment]
Made a simple splash page with a button that links to a google form for now.
Ready to be hosted on heroku/w.e

**Comment by flowstyleliving** [comment]
Actually, I'm using MongoDB so the backend isn't setup yet.

**Comment by theitsystem** [comment]
Heroku and CloudFlare are setup. Waiting on DNS to populate. The build succeeded for the master on Heroku, but the app isn't functioning. I think this is Mongo as noted above.

**Comment by flowstyleliving** [comment]
I added mLab mongo hosting, but I believe there is something up with the server script as I have not hosted a DB with a react framework yet. I will look into this further.

**Comment by theitsystem** [comment]
I don't know if this free online web datastore will help, but it's in Beta
so I added it on. https://app.objectrocket.com see Heroku settings for more
info.

On Mon, Aug 15, 2016 at 3:15 PM, Michael Young Séo <notifications@github.com

**Comment by flowstyleliving** [comment]
got it to host after many trial and errors. being deployed from my fork

**Comment by theitsystem** [comment]
You're a collaborator. You should be able to merge pull requests too no? Anyway it's off to a good start. I like it.

**Comment by flowstyleliving** [comment]
I did, but then it was auto deploying from master rather than staging.
Cool, I'll start working on a menu bar for an About, etc.
